// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/lizaiganshenmo/GoStress/conf"
	"github.com/lizaiganshenmo/GoStress/resource"
)

func main() {
	conf.Init("../../conf")
	// 加载全局变量
	resource.Init()

	h := server.Default(server.WithHostPorts(":8899"))

	register(h)
	h.Spin()
}
