// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/lizaiganshenmo/GoStress/cmd/api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	taskGroup := r.Group("/task")
	taskGroup.POST("/create", handler.CreateTask)
	taskGroup.GET("/start", handler.StartTask)
	taskGroup.GET("/stop", handler.StopTask)
	taskGroup.GET("/change_qps", handler.ChangeTaskQPS)
}
